export const keyboardSearch = [
  [
    { key: 'space', w: '262', h: 84, icon: false },
    { key: 'backspace', w: '262', h: 84, icon: false },
  ],
  [
    { key: 'a', w: 73, h: 84, icon: false },
    { key: 'b', w: 73, h: 84, icon: false },
    { key: 'c', w: 73, h: 84, icon: false },
    { key: 'd', w: 73, h: 84, icon: false },
    { key: 'e', w: 73, h: 84, icon: false },
    { key: 'f', w: 73, h: 84, icon: false },
  ],
  [
    { key: 'g', w: 73, h: 84, icon: false },
    { key: 'h', w: 73, h: 84, icon: false },
    { key: 'i', w: 73, h: 84, icon: false },
    { key: 'j', w: 73, h: 84, icon: false },
    { key: 'k', w: 73, h: 84, icon: false },
    { key: 'l', w: 73, h: 84, icon: false },
  ],
  [
    { key: 'm', w: 73, h: 84, icon: false },
    { key: 'n', w: 73, h: 84, icon: false },
    { key: 'o', w: 73, h: 84, icon: false },
    { key: 'p', w: 73, h: 84, icon: false },
    { key: 'q', w: 73, h: 84, icon: false },
    { key: 'r', w: 73, h: 84, icon: false },
  ],
  [
    { key: 's', w: 73, h: 84, icon: false },
    { key: 't', w: 73, h: 84, icon: false },
    { key: 'u', w: 73, h: 84, icon: false },
    { key: 'v', w: 73, h: 84, icon: false },
    { key: 'w', w: 73, h: 84, icon: false },
    { key: 'x', w: 73, h: 84, icon: false },
  ],
  [
    { key: 'y', w: 73, h: 84, icon: false },
    { key: 'z', w: 73, h: 84, icon: false },
    { key: '1', w: 73, h: 84, icon: false },
    { key: '2', w: 73, h: 84, icon: false },
    { key: '3', w: 73, h: 84, icon: false },
    { key: '4', w: 73, h: 84, icon: false },
  ],
  [
    { key: '5', w: 73, h: 84, icon: false },
    { key: '6', w: 73, h: 84, icon: false },
    { key: '7', w: 73, h: 84, icon: false },
    { key: '8', w: 73, h: 84, icon: false },
    { key: '9', w: 73, h: 84, icon: false },
    { key: '0', w: 73, h: 84, icon: false },
  ],
]
